spring:
  application:
    name: Neoike
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/neoike
    username: neoike
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 500
        format_sql: true
        hbm2ddl:
          auto: create
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 5MB
      enabled: true

server:
  port: 8080

logging:
  level:
    org:
      hibernate:
        SQL: debug

sneaker:
  images:
    formatTypes: .JPEG,.PNG,.JPG
    path: '/src/main/resources/sneaker/images/'


jwt:
  header: Authorization
  secret: cHJncm1zLWJlLWRldmNvdXJzZS1CRS0wMi1OZW9pa2Utc3ByaW5nLWJvb3QtYmFja2VuZC1wcm9qZWN0LWp3dC10b2tlbi1wcmdybXMtYmUtZGV2Y291cnNlLUJFLTAyLU5lb2lrZS1zcHJpbmctYm9vdC1iYWNrZW5kLXByb2plY3Qtand0LXRva2Vu
  token-validity-in-seconds: 86400